# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title

# Setup
title:            Venn
tagline:          Candid discussion on building a design-development agency
url:              http://venn.lc

author:
  name:           Venn
  url:            http://venn.lc

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/venn/venn
